name: vill_snackbar
description: Snackbar UI
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: '>=3.3.7'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
